# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
  schedule:
    - cron: "37 7 * * WED" # run at 7:37am UTC on Wednesdays

name: R-CMD-check.yaml

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}
          - {os: ubuntu-latest,   r: 'oldrel-2'}
          - {os: ubuntu-latest,   r: 'oldrel-3'}
          - {os: ubuntu-22.04-arm, r: 'release', rspm: 'no' }

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v5

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: ${{ matrix.config.rspm || 'true' }}

      - name: Install macOS system dependencies
        if: runner.os == 'macOS'
        run: brew install jags

      - name: Install Windows system dependencies
        if: runner.os == 'Windows'
        run: |
          # Install JAGS based on CRAN script
          # https://svn.r-project.org/R-dev-web/trunk/WindowsBuilds/winutf8/ucrt3/r_packages/setup_checks.ps1
          if (-not(Test-Path("C:\Program Files\JAGS\JAGS-4.3.1"))) {
            mkdir temp
            cd temp
            $url = "https://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/Windows/JAGS-4.3.1.exe/download"
            $inst = "..\installers\JAGS-4.3.1.exe"

            if (Test-Path("$inst")) {
              cp "$inst" jags.exe
            } elseif (-not(Test-path("jags.exe"))) {
              # -UserAgent "NativeHost" to work-around issues with redirects with the default
              Invoke-WebRequest -Uri "$url" -OutFile jags.exe -UseBasicParsing -UserAgent "NativeHost"
            }
            Start-Process -Wait -NoNewWindow -FilePath ".\jags.exe" -ArgumentList "/S"
            cd ..
            Remove-Item -LiteralPath "temp" -Force -Recurse
          }

      - name: Set pak options
        shell: bash
        run: echo 'options(pkg.sysreqs_db_update_timeout = as.difftime(59, units = "secs"))' >> ~/.Rprofile 
      
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, MendelianRandomization=?ignore-before-r=4.4.0
          needs: check
          upgrade: 'TRUE'

      - name: Install rstan and rjags from source on macOS
        if: runner.os == 'macOS'
        run: install.packages(c('rstan', 'rjags'), type = 'source')
        shell: Rscript {0}

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
          error-on: '"error"'
